
# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

[[constraint]]
  version = "v1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"

[[constraint]]
  revision = "5fbf1f07545e9c38750646474cf669effc6e6f75"
  name = "github.com/katzenpost/core"

[[constraint]]
  revision = "79b57ae25f58f43940729f703705c30cdb409143"
  name = "github.com/katzenpost/authority"

[[override]]
  revision = "b2d8673911ea52dcb471d3c91e7c2ae1218cf532"
  name = "github.com/katzenpost/minclient"

[[override]]
  revision = "17e5b97a06cbfbb340ec300ac11010ba2c825038"
  name = "github.com/katzenpost/client"

[[override]]
  revision = "0b8e396a52f4ff2172593f0af1f70ee951e2763c"
  name = "github.com/katzenpost/server"

# other stuff

[[override]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[override]]
  name = "github.com/abiosoft/ishell"
  version = "2.0.0"

[[override]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[override]]
  name = "github.com/ugorji/go"
  version = "1.1.1"

[[override]]
  revision = "a1dbeea552b7c8df4b542c66073e393de198a800"
  name = "github.com/hpcloud/tail"

[prune]
  go-tests = true
  unused-packages = true
