
# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

[[constraint]]
  version = "v1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"

[[constraint]]
  revision = "ebf6b0ee65d29ae5361f8882d83da6bd0031a68b"
  name = "github.com/katzenpost/core"

[[constraint]]
  revision = "aa75bd36c6debca9e28363ef7d45af3d1d3c2e7f"
  name = "github.com/katzenpost/authority"

[[override]]
  revision = "446e0edc33f9a90afd60546455f8cfa62f65eb90"
  name = "github.com/katzenpost/minclient"

[[override]]
  # master is missing reliability, will fail city
  revision = "9ef05da344143d1952bdf3651fc204d1e9739d25"
  name = "github.com/katzenpost/client"

[[override]]
  revision = "f31b1483530c6d059ed1cbd3fd3df91108907664"
  name = "github.com/katzenpost/server"

# other stuff

[[override]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[override]]
  name = "github.com/abiosoft/ishell"
  version = "2.0.0"

[[override]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[override]]
  name = "github.com/ugorji/go"
  version = "1.1.1"

[[override]]
  revision = "a1dbeea552b7c8df4b542c66073e393de198a800"
  name = "github.com/hpcloud/tail"

[prune]
  go-tests = true
  unused-packages = true
