
# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

[[constraint]]
  version = "v1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"

[[constraint]]
  revision = "44c4f4049a4317a1d5a83b43a3766cce46e6083a"
  name = "github.com/katzenpost/core"

[[constraint]]
  revision = "b4f2f222ebdc32b0ae62b2e0a97d5b1635f93702"
  name = "github.com/katzenpost/authority"

[[override]]
  branch = "add_warped_epoch_flag"
  name = "github.com/katzenpost/minclient"

[[override]]
  branch = "add_warped_epoch_flag"
  name = "github.com/katzenpost/server"

# other stuff

[[override]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[override]]
  name = "github.com/abiosoft/ishell"
  version = "2.0.0"

[[override]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[override]]
  name = "github.com/ugorji/go"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/hpcloud/tail"

[prune]
  go-tests = true
  unused-packages = true
